{"Modified": "2016-09-02T10:59:06.987-04:00", "vulnerable_configuration": [{"title": "Python 3.0", "id": "cpe:2.3:a:python:python:3.0"}, {"title": "Python 3.0.1", "id": "cpe:2.3:a:python:python:3.0.1"}, {"title": "Python 3.1.0", "id": "cpe:2.3:a:python:python:3.1.0"}, {"title": "Python 3.1.1", "id": "cpe:2.3:a:python:python:3.1.1"}, {"title": "Python 3.1.2", "id": "cpe:2.3:a:python:python:3.1.2"}, {"title": "Python 3.1.3", "id": "cpe:2.3:a:python:python:3.1.3"}, {"title": "Python 3.1.4", "id": "cpe:2.3:a:python:python:3.1.4"}, {"title": "Python 3.1.5", "id": "cpe:2.3:a:python:python:3.1.5"}, {"title": "Python 3.2.0", "id": "cpe:2.3:a:python:python:3.2.0"}, {"title": "Python 3.2.1", "id": "cpe:2.3:a:python:python:3.2.1"}, {"title": "Python 3.2.2", "id": "cpe:2.3:a:python:python:3.2.2"}, {"title": "Python 3.2.3", "id": "cpe:2.3:a:python:python:3.2.3"}, {"title": "Python 3.2.4", "id": "cpe:2.3:a:python:python:3.2.4"}, {"title": "Python 3.2.5", "id": "cpe:2.3:a:python:python:3.2.5"}, {"title": "Python 3.2.6", "id": "cpe:2.3:a:python:python:3.2.6"}, {"title": "Python 3.3.0", "id": "cpe:2.3:a:python:python:3.3.0"}, {"title": "Python 3.3.1", "id": "cpe:2.3:a:python:python:3.3.1"}, {"title": "Python 3.3.2", "id": "cpe:2.3:a:python:python:3.3.2"}, {"title": "Python 3.3.3", "id": "cpe:2.3:a:python:python:3.3.3"}, {"title": "Python 3.3.4", "id": "cpe:2.3:a:python:python:3.3.4"}, {"title": "Python 3.3.5", "id": "cpe:2.3:a:python:python:3.3.5"}, {"title": "Python Python 3.3.6", "id": "cpe:2.3:a:python:python:3.3.6"}, {"title": "Python 3.4.0", "id": "cpe:2.3:a:python:python:3.4.0"}, {"title": "Python 3.4.1", "id": "cpe:2.3:a:python:python:3.4.1"}, {"title": "Python 3.4.2", "id": "cpe:2.3:a:python:python:3.4.2"}, {"title": "Python 3.4.3", "id": "cpe:2.3:a:python:python:3.4.3"}, {"title": "Python 3.4.4", "id": "cpe:2.3:a:python:python:3.4.4"}, {"title": "Python 2.7.11", "id": "cpe:2.3:a:python:python:2.7.11"}, {"title": "Python 3.5.1", "id": "cpe:2.3:a:python:python:3.5.1"}, {"title": "cpe:2.3:a:python:python:3.5.0", "id": "cpe:2.3:a:python:python:3.5.0"}], "vulnerable_configuration_cpe_2_2": ["cpe:/a:python:python:3.0", "cpe:/a:python:python:3.0.1", "cpe:/a:python:python:3.1.0", "cpe:/a:python:python:3.1.1", "cpe:/a:python:python:3.1.2", "cpe:/a:python:python:3.1.3", "cpe:/a:python:python:3.1.4", "cpe:/a:python:python:3.1.5", "cpe:/a:python:python:3.2.0", "cpe:/a:python:python:3.2.1", "cpe:/a:python:python:3.2.2", "cpe:/a:python:python:3.2.3", "cpe:/a:python:python:3.2.4", "cpe:/a:python:python:3.2.5", "cpe:/a:python:python:3.2.6", "cpe:/a:python:python:3.3.0", "cpe:/a:python:python:3.3.1", "cpe:/a:python:python:3.3.2", "cpe:/a:python:python:3.3.3", "cpe:/a:python:python:3.3.4", "cpe:/a:python:python:3.3.5", "cpe:/a:python:python:3.3.6", "cpe:/a:python:python:3.4.0", "cpe:/a:python:python:3.4.1", "cpe:/a:python:python:3.4.2", "cpe:/a:python:python:3.4.3", "cpe:/a:python:python:3.4.4", "cpe:/a:python:python:2.7.11", "cpe:/a:python:python:3.5.1", "cpe:/a:python:python:3.5.0"], "last-modified": "2016-12-23T21:59:41.747-05:00", "map_cve_openvas": {"openvas_script_file": "gb_fedora_2016_32e5a8c3a8_python3_fc23.nasl", "openvas_script_family": "Fedora Local Security Checks", "openvas_script_id": "56466", "openvas_script_name": "Fedora Update for python3 FEDORA-2016-32e5a8c3a8"}, "map_cve_nessus": {"nessus_script_family": "Fedora Local Security Checks", "nessus_script_file": "fedora_2016-308f78b2f4.nasl", "nessus_script_id": "92329", "nessus_script_name": "Fedora 23 : python3 (2016-308f78b2f4)"}, "references": ["http://www.openwall.com/lists/oss-security/2016/06/15/15", "http://www.openwall.com/lists/oss-security/2016/06/16/1", "http://www.oracle.com/technetwork/topics/security/bulletinjul2016-3090568.html", "http://www.securityfocus.com/bid/91247", "http://www.splunk.com/view/SP-CAAAPSV", "http://www.splunk.com/view/SP-CAAAPUE", "https://bugs.python.org/issue26171", "https://docs.python.org/3.4/whatsnew/changelog.html#python-3-4-5", "https://docs.python.org/3.5/whatsnew/changelog.html#python-3-5-2", "https://hg.python.org/cpython/raw-file/v2.7.12/Misc/NEWS"], "ranking": [[{"circl": 2}]], "cwe": "CWE-190", "cvss": "10.0", "capec": [{"related_weakness": ["190", "128", "120", "122", "196", "680", "697"], "solutions": ["Use a language or compiler that performs automatic bounds checking.", "Carefully review the service's implementation before making it available to user. For instance you can use manual or automated code review to uncover vulnerabilities such as integer overflow.", "Use an abstraction library to abstract away risky APIs. Not a complete solution.", "Always do bound checking before consuming user input data."], "id": "92", "prerequisites": ["The attacker can manipulate the value of an integer variable utilized by the target host.", "The target host does not do proper range checking on the variable before utilizing it.", "When the integer variable is incremented or decremented to an out of range value, it gets a very different value (e.g. very small or negative number)"], "summary": ["This attack forces an integer variable to go out of range. The integer variable is often used as an offset such as size of memory allocation or similarly. The attacker would typically control the value of such variable and try to get it out of range. For instance the integer in question is incremented past the maximum possible value, it may wrap to become a very small, or negative number, therefore providing a very incorrect value which can lead to unexpected behavior. At worst the attacker can execute arbitrary code."], "name": "Forced Integer Overflow"}], "id": "CVE-2016-5636", "Published": "2016-09-02T10:59:06.003-04:00", "summary": "Integer overflow in the get_data function in zipimport.c in CPython (aka Python) before 2.7.12, 3.x before 3.4.5, and 3.5.x before 3.5.2 allows remote attackers to have unspecified impact via a negative data size value, which triggers a heap-based buffer overflow."}